Algoritmo "Exibir Mensagem"
//Disciplina  :  [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Exibir uma Mensagem
// Autor(a)    : Obama
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Jailson - Osasco")
Escreval("Equipe 04")
Escreval("Abner")

Fimalgoritmo